version: "3.9"
services:
  web:
    container_name: fastapi
    depends_on:
      - db
    build: .
    ports:
      - "8000:8000"
    links: 
      - "db:db"
    env_file: 
      - .env

  db:
    image: mysql
    container_name: docker-mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
      # - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    expose:
      - "3306"
    env_file: 
      - .env