version: "3.9"
services:
  web:
    container_name: fastapi
    depends_on:
      - db
    build: .
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  db:
    image: mysql
    container_name: docker-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes # https://hub.docker.com/_/mysql
